# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build-php-common: &common-build
    docker:
      - image: circleci/php:7.1-browsers
    working_directory: ~/repo
    steps:
        - run:
            name: php version
            command: php -v
        - checkout
        - run:
            name: composer install
            command: composer install
        - run:
            name: run test
            command: ./vendor/bin/kahlan
        - run:
            name: startup install
            command:  phpize && ./configure && make && sudo make install
        - run:
            name: enable startup
            command: sudo cp .circleci/docker-php-ext-startup.ini /usr/local/etc/php/conf.d/
        - run:
            name: run test
            command: ./vendor/bin/kahlan
  build-php71:
    <<: *common-build
    docker:
      - image: circleci/php:7.1-browsers
  build-php72:
    <<: *common-build
    docker:
      - image: circleci/php:7.2-browsers
  build-php70:
    <<: *common-build
    docker:
      - image: circleci/php:7.0-browsers
workflows:
  version: 2
  build:
    jobs:
      - build-php71
      - build-php72
      - build-php73
