# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    branches:
    #   only:
    #     - master # list of branches to build
    #     - develop
      ignore:
        - feature/*
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: startup install
          command:  phpize && ./configure && make && sudo make install

      - run:
          name: composer install
          command: composer install

      - run:
          name: run test
          command: ./vendor/bin/kahlan

      - run:
          name: cp docker-php-ext-start.ini
          command: sudo cp .circleci/docker-php-ext-startup.ini /usr/local/etc/php/conf.d/

      - run:
          name: enable startup
          command: sudo docker-php-ext-enable startup
      
      - run:
          name: run test
          command: ./vendor/bin/kahlan
